### ISSUE TITLE
摄像头和麦克风入会问题

### ISSUE THREAD

**Issue by Jenson-Jiang** [xylink-com/xylink-rtc-demo#1]
摄像头、麦克风入会前没有授权，入会后用户授权了，请问这个时候怎么把摄像头和麦克风连接到会议。

**Comment by luojinghui** [comment]
> 摄像头、麦克风入会前没有授权，入会后用户授权了，请问这个时候怎么把摄像头和麦克风连接到会议。

入会前拒绝授权，会推送设备权限拒绝事件，转为仅接受远端画面模式，此时，在会中操作摄像头或麦克风建议引导用户进行授权处理并重新入会。

**Comment by Jenson-Jiang** [comment]
在开会中可以从新加入设备吗？

**Comment by luojinghui** [comment]
> 在开会中可以从新加入设备吗？

可以，默认是切换到新接入的摄像头/麦克风/扬声器设备，也可以自己控制，切换开关：
http://openapi.xylink.com/api_web/client#switchautodevice 

也可以自己监听控制设备的变化和切换：
http://openapi.xylink.com/api_web/client#device
