### ISSUE TITLE
win台式机没有摄像头，入会后无法讲话

### ISSUE THREAD

**Issue by troyz** [xylink-com/xylink-rtc-demo#2]
如题，貌似sdk是强制要求必须要有audio/video的，这样其实没有考虑台式机用户web接入问题，建议做成：没有摄像头的情况下也可以入会发言，这样体验会好很多。
``` javascript
// 貌似SDK现有的逻辑：
navigator.getUserMedia({ video: true, audio: true }, ()=>{}, ()=>{});

// 期望在没有摄像头的情况下：
navigator.getUserMedia({ video: false, audio: true }, ()=>{}, ()=>{});
```

**Comment by troyz** [comment]
笔记本 可以在设备管理器中禁用摄像头测试，或者在chrome里面禁用摄像头测试
![image](https://user-images.githubusercontent.com/3285094/120076669-5582be00-c0d9-11eb-80c9-c1024d1502c0.png)

**Comment by luojinghui** [comment]
> 如题，貌似sdk是强制要求必须要有audio/video的，这样其实没有考虑台式机用户web接入问题，建议做成：没有摄像头的情况下也可以入会发言，这样体验会好很多。
> 
> ```js
> // 貌似SDK现有的逻辑：
> navigator.getUserMedia({ video: true, audio: true }, ()=>{}, ()=>{});
> 
> // 期望在没有摄像头的情况下：
> navigator.getUserMedia({ video: false, audio: true }, ()=>{}, ()=>{});
> ```

是的，现在公有云最新版v2.0.1是判断如果麦克风和摄像头其中一个有问题，就整体切换到仅接受远端画面模式，这个是之前的设计。

这个问题我们在下个版本已经处理了，麦克风和摄像头单独授权和使用。版本还在测试阶段，晚点会发布。

**Comment by luojinghui** [comment]
@troyz 此问题已经在v2.0.2+版本修复，可以更新测试；
参考发版说明：https://openapi.xylink.com/doc_web/product/version
