### ISSUE TITLE
正常install后 启动报错 ：./src/component/index.tsx Cannot find file: 'index.tsx' does not match the corresponding name on disk: '.\src\component\Audio\audio'.

### ISSUE THREAD

**Issue by dyp330** [xylink-com/xylink-rtc-demo#3]
./src/component/index.tsx
Cannot find file: 'index.tsx' does not match the corresponding name on disk: '.\src\component\Audio\audio'.

**Comment by luojinghui** [comment]
@dyp330 It has been fixed, please try again.
