### ISSUE TITLE
自定义布局

### ISSUE THREAD

**Issue by hanxiang-li** [xylink-com/xylink-rtc-demo#4]
```
<a-layout>
    <a-layout>
      <div id="layout" class="layout"></div>
    </a-layout>
    <a-layout-sider>
      <rx-video v-for="item in videoList" :key="item.id" :data="item"/>
    </a-layout-sider>
  </a-layout>
 ```
 client = xyRTC.createClient({
    layout: 'CUSTOM',
    clientId: ACCOUNT.clientId,
    container: {
      elementId: 'layout'
    }
  });
这直接把body清空了，我不想让SDK 这样控制布局，是否有解决方案？

**Comment by luojinghui** [comment]
> 

没太理解，具体的布局需求是什么呢？

可以看看自定义模式：https://openapi.xylink.com/common/meeting/doc/stream_v2?platform=web
