### ISSUE TITLE
web Rtc 3.8.0版本无法加入Mac Safari浏览器

### ISSUE THREAD

**Issue by Jenson-Jiang** [xylink-com/xylink-rtc-demo#6]
Safari版本：14.0.1 (16610.2.11.51.8)
IOS手机和PC问题都存在；
问题描述：点击加入会议返回错误，not support webrt

**Comment by luojinghui** [comment]
@Jenson-Work 
小鱼易连WebRTC SDK默认是支持Mac Safari浏览器，但在入会检测方法里面禁用了Safari的入会能力，因为它的体验没有chrome/edge/firefox好，如果你想测试入会效果，可以在SDK Demo中：
https://github.com/xylink-com/xylink-rtc-demo/blob/master/src/view/index.tsx#L978
移除入会前的support能力检测，这样就可以正常入会；

移动端iOS是默认支持入会，没有做限制；
