### ISSUE TITLE
支持uni-app vue3，或者vue3.0吗，有类似demo吗

### ISSUE THREAD

**Issue by llk-web** [xylink-com/xylink-rtc-demo#7]

**Comment by luojinghui** [comment]
@llk-web 
小鱼WebRTC SDK库可以在任意的框架下集成，vue3.0、react、electron等，这些都没有限制。

vue2.x的demo可以参考：https://github.com/xylink-com/xylink-rtc-vue-demo

vue3可以参考vue2，需要将对应语法转一下即可
