### ISSUE TITLE
meeting-control的muteOperation和会议号的默认入会的麦克风状态不一致

### ISSUE THREAD

**Issue by Jenson-Jiang** [xylink-com/xylink-rtc-demo#8]
<img width="855" alt="image" src="https://github.com/xylink-com/xylink-rtc-demo/assets/65748040/0d83d031-aba8-4f63-80da-b613411a5f4c">
议号的麦克风和web sdk muteOperation状态存在不一致的问题：的autoMute状态为2时，muteOperation的状态为muteAudio，当为1时返回的状态为空字符串

**Comment by luojinghui** [comment]
可以通过监听audio-status事件获取最终的麦克风状态：
https://openapi.xylink.com/common/meeting/api/client?platform=web#h0613ccc-DNDM66Rx
